database:
  host: localhost
  username: 2si
  password: passer
  database: 2si
smtp_server:
  address: smtp.alwaysdata.com
  port: 25
  user_name: demo@scicasoft.com
  password: scicademopass!!!
  label: '2sinotif'
directories:
  - /home/scicasoft/Bureau/2si/test1
  - /home/scicasoft/Bureau/2si/test2
mails_notif:
  - scicasoft@gmail.com
  - sidya.camara@gmail.com