frequence_cron: 60
database:
  adapter: mysql2
  host: localhost
  username: 2si
  password: passer
  database: 2si
smtp_server:
  address: smtpgp1-med.orange.sn
  port: 25
  user_name: demo@test.com
mails_notif:
  - username1@domain.ext
  - username2@domain.ext
  - scicasoft@gmail.com